apiVersion: v1
kind: Pod
metadata:
  name: pod-with-taint-no-schedule
spec:
  tolerations:
  - key: "customerMachine"
    operator: "Equal"
    value: "C1"
    effect: "NoSchedule"
  containers:
    - name: nginx
      image: nginx:latest
      ports: 
        - containerPort: 80