apiVersion: v1
kind: Pod
metadata:
  name: pod-using-secret
spec:
  containers:
  - name: redis-container
    image: redis:latest
    volumeMounts:
    - name: secret-from-kubernetes
      mountPath: "/my-secret-path"
      readOnly: true
  volumes:
  - name: secret-from-kubernetes
    secret:
      secretName: mysecret-mixing-base64-text-plain