apiVersion: v1
kind: Pod
metadata:
  name: pod-using-secret-with-custom-paths
spec:
  containers:
  - name: redis-using-secret-with-custom-path
    image: redis
    volumeMounts:
    - name: volume-for-db-credentials
      mountPath: "/my-beautifoul-path/data"
      readOnly: true
  volumes:
  - name: volume-for-db-credentials
    secret:
      secretName: db-access
      items:
      - key: username.txt
        path: credentials/my-login-username