apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-filepermission
spec:
  containers:
  - name: container-with-nginx
    image: nginx
    volumeMounts:
    - name: my-beautifoul-volume
      mountPath: "/my-secrets-password-path"
  volumes:
  - name: my-beautifoul-volume
    secret:
      secretName: db-access
      defaultMode: 511