apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-with-env-variables
spec:
  containers:
  - name: nginx-container
    image: nginx
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-access
          key: username.txt
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-access
          key: password.txt
  restartPolicy: Never