apiVersion: v1
kind: Pod
metadata:
  name: pod-with-labels
  labels:
    customer: C8229565
    app: frontend
    version: v2
spec:
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80